# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d . --bc-api-key e516a5ad-1eb5-4de3-bcdf-0474a8e6f749::renxpITXZWmrVRqdmbIWTn9nlqQ= --branch main
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: https://api3.prismacloud.io

